### ISSUE TITLE
Android P Crash

### ISSUE THREAD

**Issue by alenz316** [mparticle-integrations/mparticle-android-integration-singular#3]
Our application is crashing on startup when running on Android P Developer Preview 3 + 4 (Beta 2 + 3 respectively) with the latest version of mParticle and the Singular kit `5.3.6`

```
07-03 08:42:24.263 8031-8031/com.package.name E/Singular: Singular [main] - Exception
    java.lang.NullPointerException: Attempt to invoke virtual method 'void com.singular.sdk.internal.SessionManager.onEnterForeground(long)' on a null object reference
        at com.singular.sdk.internal.SingularInstance.onActivityResumed(SingularInstance.java:299)
        at com.singular.sdk.Singular.onActivityResumed(Singular.java:216)
        at com.mparticle.kits.SingularKit.onActivityResumed(SingularKit.java:102)
        at com.mparticle.kits.KitManagerImpl.initializeKit(KitManagerImpl.java:226)
        at com.mparticle.kits.KitManagerImpl.configureKits(KitManagerImpl.java:174)
        at com.mparticle.kits.KitManagerImpl$UpdateKitRunnable.run(KitManagerImpl.java:131)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by samdozor** [comment]
hey @alenz316 looks like we're on the latest version of the singular SDK itself (7.3.3). I imagine they'll be pushing an update to their SDK once Android P is generally available, at which time we'll update the dependency in the kit.
